#!/bin/sh

if [ `machtype`x != "sgix" ]; then
	/bin/stty dec
fi

TERMCAP="vs|xterm|vs100|xterm terminal emulator (X window system):cr=^M:do=^J:nl=^J:bl=^G:le=^H:ho=\E[H:co#80:li#24:cl=\E[H\E[2J:bs:cm=\E[%i%d;%dH:nd=\E[C:up=\E[A:ce=\E[K:cd=\E[J:so=\E[7m:se=\E[m:us=\E[4m:ue=\E[m:md=\E[1m:mr=\E[7m:me=\E[m:ku=\EOA:kd=\EOB:kr=\EOC:kl=\EOD:kb=^H:k1=\EOP:k2=\EOQ:k3=\EOR:k4=\EOS:ta=^I:pt:sf=\n:sr=\EM:al=\E[L:dl=\E[M:ic=\E[@:dc=\E[P::MT:ks=\E[?1h\E=:ke=\E[?1l\E>:is=\E[r\E[m\E[2J\E[H\E[?7h\E[?1;3;4;6l::rs=\E[r\E<\E[m\E[2J\E[H\E[?7h\E[?1;3;4;6l:xn:AL=\E[%dL:DL=\E[%dM:IC=\E[%d@:DC=\E[%dP:ti=\E7\E[?47h:te=\E[2J\E[?47l\E8:hs:ts=\E[?E\E[?%i%dT:fs=\E[?F:es:ds=\E[?E:"
export TERMCAP

cd /mit/register

/mit/register/arch/@sys/bin/xterm -geometry 80x24+128+128 \
	-display unix:0.0 -ut -rv \
	-fn -adobe-courier-bold-r-\*-\*-\*-140-\* \
	-xrm "xterm*VT100*Translations: #override \n <ButtonPress>: bell(0) \n <ButtonRelease>: ignore() \n <Map>: secure()" \
	-e /mit/register/arch/@sys/bin/userreg

/bin/athena/detach -n -q -h register &

exit 0
