CREATE INDEX i_usr_login ON users (login) 
CREATE INDEX i_usr_name ON users (first, last)
CREATE INDEX i_usr_last ON users (last, first)
CREATE INDEX i_usr_uid ON users (uid)
CREATE INDEX i_usr_pop ON users (pop_id)
CREATE INDEX i_krb_str ON krbmap  (string_id)
CREATE INDEX i_mac_name ON machine (name)
CREATE INDEX i_clu_name ON cluster (name)
CREATE INDEX i_mcm_mach ON mcmap (mach_id)
CREATE INDEX i_sho_mach ON serverhosts (mach_id)
CREATE INDEX i_lis_name ON list(name)
CREATE INDEX i_lis_mail ON list (maillist)
CREATE INDEX i_lis_group ON list (group)
CREATE INDEX i_lis_gid ON list (gid)
CREATE INDEX i_imem_list ON imembers (list_id)
CREATE INDEX i_str_name ON strings (string)
CREATE INDEX i_nfs_mach ON nfsphys (mach_id)
CREATE INDEX i_fil_name ON filesys (label)
CREATE INDEX i_fil_mach ON filesys (mach_id)
CREATE INDEX i_fil_phys ON filesys (phys_id)
CREATE INDEX i_fil_grp ON filesys (owners)
CREATE INDEX i_fil_user ON filesys (owner)
CREATE INDEX i_fsg_filsys ON fsgroup (filsys_id)
CREATE INDEX i_qot_fil ON quota (filsys_id)
CREATE INDEX i_qot_phys ON quota (phys_id)
CREATE INDEX i_pcp_mach ON printcap (mach_id)
