create table users
(
        login		VARCHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	users_id	INTEGER		DEFAULT 0	NOT NULL,
	unix_uid	SMALLINT 	DEFAULT 0	NOT NULL,
	shell		CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	last		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	first		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	middle		CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	status		SMALLINT 	DEFAULT 0	NOT NULL,
	clearid		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	type		CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	comments        INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	fullname	CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	nickname	CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	home_addr	CHAR(82) 	DEFAULT CHR(0)	NOT NULL,
	home_phone	CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	office_addr	CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	office_phone	CHAR(12) 	DEFAULT CHR(0)	NOT NULL,
	department	CHAR(20) 	DEFAULT CHR(0)	NOT NULL,
	affiliation	CHAR(50) 	DEFAULT CHR(0)	NOT NULL,
	fmodtime	DATE    	DEFAULT SYSDATE	NOT NULL,
	fmodby		INTEGER		DEFAULT 0	NOT NULL,
	fmodwith	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	potype		CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	pop_id		INTEGER		DEFAULT 0	NOT NULL,
	box_id		INTEGER		DEFAULT 0	NOT NULL,
	pmodtime	DATE    	DEFAULT SYSDATE	NOT NULL,
	pmodby		INTEGER		DEFAULT 0	NOT NULL,
	pmodwith	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	xname           CHAR(30)        DEFAULT CHR(0)	NOT NULL,
	xdept        	CHAR(20)        DEFAULT CHR(0)	NOT NULL,
	xtitle       	CHAR(50)	DEFAULT CHR(0)	NOT NULL,
	xaddress     	CHAR(82)	DEFAULT CHR(0)	NOT NULL,
	xphone1      	CHAR(12)	DEFAULT CHR(0)	NOT NULL,
	xphone2      	CHAR(12)	DEFAULT CHR(0)	NOT NULL,
	xmodtime     	DATE         	DEFAULT SYSDATE	NOT NULL,
	sigdate      	INTEGER		DEFAULT 0	NOT NULL,
	sigwho       	INTEGER		DEFAULT 0	NOT NULL,
	signature    	VARCHAR(68)	DEFAULT CHR(0)	NOT NULL,
	secure       	INTEGER		DEFAULT 0	NOT NULL,       
	flag         	INTEGER		DEFAULT 0	NOT NULL
);

create table krbmap
(
	users_id	INTEGER		DEFAULT 0	NOT NULL,
	string_id	INTEGER		DEFAULT 0	NOT NULL
);

create table machine
(
	name		VARCHAR(40) 	DEFAULT CHR(0)	NOT NULL,
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	vendor		CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	model		CHAR(24) 	DEFAULT CHR(0)	NOT NULL,
	os		CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	location	CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	contact		CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	use		INTEGER		DEFAULT 0	NOT NULL,
	status		INTEGER		DEFAULT 0	NOT NULL,
	statuschange	DATE    	DEFAULT SYSDATE	NOT NULL,
	snet_id		INTEGER		DEFAULT 0	NOT NULL,
	address		CHAR(16)	DEFAULT CHR(0)	NOT NULL,
	owner_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	owner_id	INTEGER		DEFAULT 0	NOT NULL,
	acomment	INTEGER		DEFAULT 0	NOT NULL,
	ocomment	INTEGER		DEFAULT 0	NOT NULL,
	created		DATE 		DEFAULT SYSDATE	NOT NULL,
	creator		INTEGER		DEFAULT 0	NOT NULL,
	inuse		DATE		DEFAULT SYSDATE	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table hostalias
(
	name		VARCHAR(40) 	DEFAULT CHR(0)	NOT NULL,
	mach_id		INTEGER	 	DEFAULT 0	NOT NULL
);

create table subnet
(
	name		CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	snet_id		INTEGER		DEFAULT 0	NOT NULL,
	description	VARCHAR(48) 	DEFAULT CHR(0)	NOT NULL,
	saddr		INTEGER		DEFAULT 0	NOT NULL,
	mask		INTEGER		DEFAULT 0	NOT NULL,
	low		INTEGER		DEFAULT 0	NOT NULL,
	high		INTEGER		DEFAULT 0	NOT NULL,
	prefix		CHAR(8)		DEFAULT CHR(0)	NOT NULL,
	owner_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	owner_id	INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE 		DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table clusters
(
	name		VARCHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	clu_id		INTEGER		DEFAULT 0	NOT NULL,
	description	CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	location	CHAR(64) 	DEFAULT CHR(0)	NOT NULL,
	modtime	 	DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table mcmap
(
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	clu_id		INTEGER		DEFAULT 0	NOT NULL
);

create table svc
(
	clu_id		INTEGER		DEFAULT 0	NOT NULL,
	serv_label	VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	serv_cluster	CHAR(32) 	DEFAULT CHR(0)	NOT NULL
);

create table list
(
	name		VARCHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	list_id		INTEGER		DEFAULT 0	NOT NULL,
	active		INTEGER 	DEFAULT 0	NOT NULL,
	publicflg	INTEGER 	DEFAULT 0	NOT NULL,
	hidden		INTEGER 	DEFAULT 0	NOT NULL,
	maillist	INTEGER 	DEFAULT 0	NOT NULL,
	grouplist	INTEGER 	DEFAULT 0	NOT NULL,
	gid		SMALLINT 	DEFAULT 0	NOT NULL,
	description	CHAR(255) 	DEFAULT CHR(0)	NOT NULL,
	acl_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	acl_id		INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table imembers 
(
	list_id		INTEGER		DEFAULT 0	NOT NULL,
	member_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	member_id	INTEGER		DEFAULT 0	NOT NULL,
	ref_count	SMALLINT 	DEFAULT 0	NOT NULL,
	direct		SMALLINT 	DEFAULT 0	NOT NULL
);

create table servers 
(
	name		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	update_int	INTEGER		DEFAULT 0	NOT NULL,
	target_file	CHAR(64) 	DEFAULT CHR(0)	NOT NULL,
	script		CHAR(128) 	DEFAULT CHR(0)	NOT NULL,
	dfgen		INTEGER		DEFAULT 0	NOT NULL,
	dfcheck		INTEGER		DEFAULT 0	NOT NULL,
	type		CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	enable		INTEGER 	DEFAULT 0	NOT NULL,
	inprogress	INTEGER 	DEFAULT 0	NOT NULL,
	harderror	INTEGER		DEFAULT 0	NOT NULL,
	errmsg		CHAR(80) 	DEFAULT CHR(0)	NOT NULL,
	acl_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	acl_id		INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0) 	NOT NULL
);

create table serverhosts 
(
	service		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	success		INTEGER 	DEFAULT 0	NOT NULL,
	enable		INTEGER 	DEFAULT 0	NOT NULL,
	override	INTEGER 	DEFAULT 0	NOT NULL,
	inprogress	INTEGER 	DEFAULT 0	NOT NULL,
	hosterror	INTEGER		DEFAULT 0	NOT NULL,
	hosterrmsg	CHAR(80) 	DEFAULT CHR(0)	NOT NULL,
	ltt		INTEGER		DEFAULT 0	NOT NULL,
	lts		INTEGER		DEFAULT 0	NOT NULL,
	value1		INTEGER		DEFAULT 0	NOT NULL,
	value2		INTEGER		DEFAULT 0	NOT NULL,
	value3		CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table filesys 
(
	filsys_id	INTEGER		DEFAULT 0	NOT NULL,
	phys_id		INTEGER		DEFAULT 0	NOT NULL,
	label		VARCHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	fs_order	INTEGER		DEFAULT 0	NOT NULL,
	type		CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	name		VARCHAR(80) 	DEFAULT CHR(0)	NOT NULL,
	mount		CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	rwaccess	CHAR(1) 	DEFAULT CHR(0)	NOT NULL,
	comments	CHAR(64) 	DEFAULT CHR(0)	NOT NULL,
	owner		INTEGER		DEFAULT 0	NOT NULL,
	owners		INTEGER		DEFAULT 0	NOT NULL,
	createflg	INTEGER 	DEFAULT 0	NOT NULL,
	lockertype	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0) 	NOT NULL
);

create table fsgroup
(
	group_id	INTEGER		DEFAULT 0	NOT NULL,
	filsys_id	INTEGER		DEFAULT 0	NOT NULL,
	key		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table nfsphys 
(
	nfsphys_id	INTEGER		DEFAULT 0	NOT NULL,
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	device		CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	dir		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	status		SMALLINT 	DEFAULT 0	NOT NULL,
	allocated	INTEGER		DEFAULT 0	NOT NULL,
	partsize	INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table quota 
(
	filsys_id	INTEGER		DEFAULT 0	NOT NULL,
	type		CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	entity_id	INTEGER		DEFAULT 0	NOT NULL,
	phys_id		INTEGER		DEFAULT 0	NOT NULL,
	quota		INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0) 	NOT NULL
);

create table zephyr 
(
	class		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	xmt_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	xmt_id		INTEGER		DEFAULT 0	NOT NULL,
	sub_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	sub_id		INTEGER		DEFAULT 0	NOT NULL,
	iws_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	iws_id		INTEGER		DEFAULT 0	NOT NULL,
	iui_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	iui_id		INTEGER		DEFAULT 0	NOT NULL,
	modtime 	DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0) 	NOT NULL
);

create table hostaccess 
(
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	acl_type	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	acl_id		INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table strings 
(
	string_id	INTEGER		DEFAULT 0	NOT NULL,
	string		VARCHAR(128)	DEFAULT CHR(0)	NOT NULL
);

create table services 
(
	name		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	protocol	CHAR(8) 	DEFAULT CHR(0)	NOT NULL,
	port		SMALLINT 	DEFAULT 0	NOT NULL,
	description	CHAR(64) 	DEFAULT CHR(0)	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0) 	NOT NULL
);

create table printcap 
(
	name		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	dir		CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	rp		CHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	quotaserver	INTEGER		DEFAULT 0	NOT NULL,
	auth		INTEGER 	DEFAULT 0	NOT NULL,
	price		SMALLINT 	DEFAULT 0	NOT NULL,
	comments	CHAR(64) 	DEFAULT CHR(0)	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table palladium
(
	name		VARCHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	identifier	INTEGER		DEFAULT 0	NOT NULL,
	mach_id		INTEGER		DEFAULT 0	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	modby		INTEGER		DEFAULT 0	NOT NULL,
	modwith		CHAR(8) 	DEFAULT CHR(0)	NOT NULL
);

create table capacls 
(
	capability	CHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	tag		CHAR(4) 	DEFAULT CHR(0)	NOT NULL,
	list_id		INTEGER		DEFAULT 0	NOT NULL
);

create table alias 
(
	name		VARCHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	type		VARCHAR(16) 	DEFAULT CHR(0)	NOT NULL,
	trans		VARCHAR(128) 	DEFAULT CHR(0)	NOT NULL
);

create table numvalues 
(
	name		VARCHAR(32) 	DEFAULT CHR(0)	NOT NULL,
	value		INTEGER		DEFAULT 0	NOT NULL
);

create table tblstats 
(
	table_name	CHAR(16)	DEFAULT CHR(0)	NOT NULL,
	modtime		DATE    	DEFAULT SYSDATE	NOT NULL,
	appends		INTEGER		DEFAULT 0	NOT NULL,
	updates		INTEGER		DEFAULT 0	NOT NULL,
	deletes		INTEGER		DEFAULT 0	NOT NULL
);

create table incremental
(
	table_name	CHAR(16)	DEFAULT CHR(0)	NOT NULL,
	service		CHAR(16) 	DEFAULT CHR(0)	NOT NULL
);
