# $Header: /afs/.athena.mit.edu/astaff/project/moiradev/repository/moira/clients/moira/Doc/Makefile,v 1.1 1996-07-02 02:01:45 danw Exp $

all: internal.PS

internal.PS: internal.mss
	scribe internal

clean:
	rm -f *.PS *.err *.aux *.otl
