# $HeadURL: svn+ssh://svn.mit.edu/moira/trunk/moira/clients/moira/Doc/Makefile $ $Id: Makefile 3956 2010-01-05 20:56:56Z zacheiss $

all: internal.PS

internal.PS: internal.mss
	scribe internal

clean:
	rm -f *.PS *.err *.aux *.otl
