
all: mit/moira/libmoirajava.so

moirai.o: moirai.c mit_moira_MoiraConnectInternal.h
	gcc -I/usr/java/include -I/usr/java/include/solaris -I/alt/jis/moira/include -I/usr/athena/include -I/alt/jis/moira/lib -g -c moirai.c -Wall


mit/moira/libmoirajava.so: moirai.o
	gcc -G -o libmoirajava.so moirai.o -L /alt/jis/moira/lib -lmoira -L/usr/athena/lib -lhesiod -lkrb4 -lkrb5 -lcom_err -ldes425 -lcrypto
	cp -p libmoirajava.so libmoirajava_g.so
	mv libmoirajava* mit/moira/

