#!/bin/sh
#
#  Script to update Moira from Registrar's "tapes".

date=`date +%y%m%d`
##### date=`expr $date - 1` # files are postdated by 1 day

cd /moira/ || exit 1
for who in  staff student ; do
  if  [ -f tapes/$who.input.$date.Z ] ; then
    [ -s $who.input ] \
    && mv $who.input.0 $who.input.1 \
    && mv $who.input   $who.input.0

    zcat tapes/$who.input.$date.Z | bin/$who.cvt > $who.input

    [ -s $who.input ] \
    && [ `diff $who.input.0 $who.input | wc -l` -lt 500 ] \
    && bin/$who -n $who.input > $who.output.$date 2>&1 \
    && egrep -v "($who): (adding|updating)" $who.output.$date > $who.err 2>&1 \
    && cat /usr/local/lib/mail_header $who.err | mail dkk
  fi
done
