.TH CHPOBOX 1 "5 Feb 1988" "Project Athena"
\" RCSID: $Header: /afs/.athena.mit.edu/astaff/project/moiradev/repository/moira/man/chpobox.1,v 1.2 1988-11-29 14:40:09 mar Exp $
.SH NAME
chpobox \- change where user receives mail
.SH SYNOPSIS
.B chpobox
[-s address][-p][-u username]
.SH DESCRIPTION
This command sets and displays the mailbox currently assigned to
.IR username
(your own name by default).
If neither the
.B -s
or the
.B -p
option is given, the current mailbox will be displayed.  
The
.B -s
option will attempt to set the user's mailbox to the specified address.
The 
.B -p
flag will set the user's mailbox to the last Post Office server it was
using if the mailbox is now a foreign address.
.PP
A mailbox address is of the form
.I string@hostname,
where the string is usually the username, and the hostname is the name
of the machine the user wishes to receive mail on.
.B chpobox
will determine if the mailbox is of type POP, LOCAL, or FOREIGN based
on information in the SMS database, and then make the appropriate
change in the SMS database.
It will not allow a user to have more than one mailbox of any type.
The actual change will not take place on the mail hub for several hours.
Users may only change their own information unless they are
SMS database administrators.
.SH "SEE ALSO"
sms(1),
SMS Section of the Project Athena Technical Plan.
