.TH MAILMAINT 1 "27 Apr 1994" "MIT Athena"
\" RCSID: $HeadURL: svn+ssh://svn.mit.edu/moira/trunk/moira/man/mailmaint.1 $ $Id: mailmaint.1 3956 2010-01-05 20:56:56Z zacheiss $
.SH NAME
mailmaint \- maintain mailing lists for a user
.SH SYNOPSIS
.B mailmaint
.SH DESCRIPTION
.I maintmaint
allows a user to examine public mailing lists and add or
remove him/herself from such lists.  It does this using Moira, the Athena
Service Management System.
.PP
When started, it will display a menu with the following options:
.in +5
.nf
1. Show all mailing lists.
2. Get all members of a mailing list.
3. Display lists of which you are a member.
4. Show description of list.
5. Add yourself to a mailing list.
6. Delete yourself from a mailing list.
.in -5
.fi
.PP
The first option will display all mailing lists that are not
explicitly hidden.  The second option will display the members of a
named list.  The third will display the names of the lists you belong
to.  The next option will give a description of any list that you
name.
.PP
The next two options allow you to add or delete yourself to or from
public mailing lists.  If the person creating a mailing list has not
made it public, you will not be allowed to add yourself to it.  Even if it is
public, you can only add or delete yourself, you cannot affect the
others on the list.  For other list operations (which are only allowed
to the administrators of a list), see 
.I listmaint(1).
.SH MENU OPERATION
The menu works in the following way:  A list of possible choices is
presented, each preceded by a number.  To make a choice, press the
number of the choice, which will then be highlighted.  To confirm this
choice, press the return key.
.PP
If information is needed that cannot be entered via a menu (e.g. a
description of the mailing list's purpose and/or use), the user will be
prompted for such information.
.PP
Typing the interrupt character (normally Ctrl-C) 
during a text input will cancel the operation and return to
the menu.
.SH ENVIRONMENT
.TP
KRBTKFILE
path name of your Kerberos ticket.  Moira decides who you are and what you
can do based on your Kerberos tickets, and nothing else.
.TP
TERMCAP
information about the capabilities of the terminal and how to use them.
.SH SEE ALSO
listmaint(1)
.SH AUTHOR
Peter J. Levine, MIT Project Athena
