.TH SMSTEST 8 "25 Jan 1988" "Project Athena"
\" RCSID: $Header: /afs/.athena.mit.edu/astaff/project/moiradev/repository/moira/man/mrtest.8,v 1.5 1989-08-16 11:29:38 mar Exp $
.SH NAME
smstest \- perform SMS operations manually
.SH SYNOPSIS
.B smstest
.SH DESCRIPTION
.I smstest
allows one to perform by hand all operations allowed in the sms
protocol.  There are no command line options, as commands are given to
a prompt within the program.  Control operations are:
.TP
.B connect [server]
make a network connection to the SMS server.  If no server is
specified, the default "SMS.MIT.EDU:sms_db" will be used.
.TP
.B disconnect
break the network connection to the SMS server.
.TP
.B host
show the name of the host the client is connected to.
.TP
.B new
specify use of version 2.0 of the protocol.
.TP
.B old
specify use of version 1.0 of the protocol.
.TP
.B script inputfile [outputfile]
read commands from 
.I inputfile.
If
.I outputfile
is specified, output will be redirected there while
commands are read from
.I inputfile.
The script file may contain comments consisting of lines starting
with a percent sign.  Script files may also recursively perform other
script commands up to 8 scripts deep.
.TP
.B list_requests
lists all of the 
.I smstest
commands.
.TP
.B quit
exits the program.
.PP
SMS protocol operations include:
.TP
.B noop
does "no operation" to the server, just making sure the server is
still there.
.TP
.B auth
sends
.I Kerberos
tickets to the server to authenticate the user.
.TP
.B query query_handle [query arguments ...]
performs a query operation on the server.  All of the real work is
done in queries.  There are over 100 queries, each of which requires
different arguments.  the arguments should be placed on the line
following the name of the query, separated by whitespace.
.TP
.B access query_handle [query arguments ...]
performs an authorization check on a query without actually executing
the query.  The arguments are the same as those in the
.B query
command described above.
.TP
.B dcm
instructs the server to trigger a DCM update immediately.
.SH BUGS
Due to problems in the ss library, standard input must be a terminal.
If it is a file, only the first line will be read.  However, the
script command allows one to read input from a file.
.SH SEE ALSO
The Project Athena Technical Plan section on SMS for a list of queries
and their arguments, and a description of the protocol this
implements.
