.TH REG_SVR 8 "30 Nov 1988" "Project Athena"
\" RCSID: $Header: /afs/.athena.mit.edu/astaff/project/moiradev/repository/moira/man/reg_svr.8,v 1.3 1988-12-06 14:35:34 mar Exp $
.SH NAME
reg_svr, startreg \- SMS account registration server
.SH SYNOPSIS
.B reg_svr
.br
.B startreg
.SH DESCRIPTION
The registration server
must be running on the machine hosting the SMS database for the 
.I userreg
program to function.  Rather than invoke
.B reg_svr
directly, it is started by
.B startreg,
which starts the daemon running in the proper working directory and
captures logging messages.
.PP
Logging is done to standard output.
If critical errors are detected, they are logged to
.B /u1/sms/critical.log
and in a zephyrgram to class
.B SMS
instance
.B REG_SVR
in addition to standard output.
Also, a journal file is kept in
.B /u1/sms/journal.reg
logging every successful change of the database in a format that can
be replayed by
.I smstest(8).
For the server to be able to function properly, if must be run as root
and root must have access to the tables through RTI Ingres.  Also,
Kerberos principal "register.sms" must have permission to create new
Kerberos principals and set their passwords.
.PP
.B startreg
sets its working directory to the root, disconnects from the terminal
and puts itself in the background.  It then starts
.B /u1/sms/bin/reg_svr,
and will capture lines the server writes to standard output and log them
in
.B /u1/sms/reg_svr.log
along with a timestamp.
.B startreg
will also log the exit status of the
.B reg_svr
if it is non-zero.
.SH FILES
/u1/sms/reg_svr.log
.br
/u1/sms/critical.log
.br
/u1/sms/journal.reg
.br
.br
/tmp/tkt_ureg \- temporary Kerberos ticket storage.
.br
/etc/srvtab \- The dcm must be able to get Kerberos tickets for "register.sms".
.SH AUTHORS
Jay Berkenbilt, Bill Sommerfeld
.SH "SEE ALSO"
userreg(1), The Project Athena Technical Plan section on SMS.
