.TH USERREG 1 "30 Nov 1988" "Project Athena"
\" RCSID: $HeadURL$ $Id$
.SH NAME
userreg \- create an account for a person known to Moira
.SH SYNOPSIS
.B userreg
.SH DESCRIPTION
.B userreg
will take over the terminal, and in a user friendly way ask for the
user's full name and ID number, then allow them to chose a login name
and a password and create their account.  All access to the Moira
database and Kerberos server is through the
.B reg_svr
running on the Moira server machine.  Many of the screens of helpful
text that are displayed for the user are contained in text files in
the working directory of
.B userreg.
.PP
When
.B userreg
first starts, it checks the file
.B disabled.times
to determine if it is allowed to register people now.  This file
contains lines in
.I crontab
format indicating times when users are not allowed to register.  The
command field of these lines contain a text message that is displayed
if there is a match for the time interval on that line.
.SH FILES
disabled.times
.br
/mit/register/welcome
.br
/mit/register/network_down
.br
/mit/register/username_blurb
.br
/mit/register/password_blurb
.br
/mit/register/deleted_acct
.br
/mit/register/not_allowed
.br
/mit/register/improper_reg
.SH SEE ALSO
reg_svr(8),
The Project Athena Technical Plan section on Moira
